### ISSUE TITLE
Metrics problems

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1296]
+ user activity currently disregards sharing, if I do a bunch of work in a shared folder that "activity" will contribute to the owner's folder's active state.
+ we should probably measure how many people use sharing

**Comment by Parth** [comment]
Our metrics are defined and calculated in https://github.com/lockbook/lockbook/blob/master/server/server/src/metrics.rs. This is an example of logic that we used to try to write in sql and we're much happier to have written it in Rust.

Checkout how the various fields are calculated, explore how trees are created and what questions we can ask a tree. 

One of our most important metrics is "active users", and we want to be more strict about how we're counting and calculating active users. Currently there's 2 known problems with active users:
+ all members of a shared folder are being marked as active when anyone modifies something in a shared folder
+  new users are being marked as active even if they didn't author a file.

We want to be strict about this metric because I feel like it's the single number that captures how well we're doing, I'm sure we can convince a large number of people to try the app, but we want to see how many people are returning to the app and making it a part of their daily routine. Our second most important metric is probably premium users.

So we could fix the way active users are being calculated by doing the following:
+ Determining if _they_ modified the file in that file tree within the last 2 days. Which means modifying [this](https://github.com/lockbook/lockbook/blob/master/server/server/src/metrics.rs#L164-L166) to filter out changes by other people.
+ We could also filter out people if the only file that was changed in the last 2 days was their root, (see `.is_root()`).

This would be a 90% solution, try to take a moment to see if you can figure out under what circumstances this would not work well.

Answer:

If user A edits a file, they're active. If user B edits that same file 1 hour later, they "overwrite" the fact that user A was active.

So to answer this question properly we don't have all the data readily available, we need to store more information in our database.

I believe we're going to want to store an additional table that tracks which public_keys were _seen last_.

The schema for our server's database is defined [here](https://github.com/lockbook/lockbook/blob/master/server/server/src/schema.rs#L48). Take a moment to observe what's going on here. There's a bit of messiness introduced by hmdb that I (maybe you) will fix soon, but it's a good look into how things happen. So there's 2 schemas here, an older v1, and a v2. We added 2 "tables" to our database in v2. Similarly you're probably going to add a `last_seen: <Owner, u64>`. But you're not going to add it to `V2` you're going to define a `V3`. And then you're going to migrate data from `V2` -> `V3` there's an example of this in that file.

For your reference the messiness introduced by hmdb is the following:
+ `v2` needs to be in it's own mod
+ added tables need migrations even though they're not breaking changes

These will get cleaned up in the near future.

While you're here you should see how `v2::migrate()` is called. You can delete the `v2` migration, and the `v1` schema definition as this code has already run and our database has been migrated on the server to v2 already. In core we must always leave these around so that people on older versions can always upgrade to newer ones. But in the server once we're migrated we're done. Make sure you understand this idea fully.

Once you've defined a new table, now you need to determine where to update these fields. I suggest you capture a last seen anytime a user `upsert`'s a file, or `write`'s a file. I'm intentionally trying to exclude as much as possible here, so no `get_updates` or `get_document` no read operations. You should browse all the endpoints and understand them.

At this point, you have the data, you've updated it, now you just need to read it in metrics and update the the field properly.

I also want to keep track of the number of people participating in sharing. I believe the way to do this would be to count the number of metas in a tree that have more than one `user_access_key`. @tvanderstad to confirm.

So this task is:
+ [ ] fix active users
+ [ ] capture metrics on sharing
+ [ ] update grafana to show sharing metrics alongside existing metrics

**Comment by tvanderstad** [comment]
>I also want to keep track of the number of people participating in sharing. I believe the way to do this would be to count the number of metas in a tree that have more than one `user_access_key`
Not quite. To recap our encryption model, each file has a (symmetric) encryption key. For documents, it's the key used to encrypt the document contents, and for all files it's used to encrypt the file name. The file keys are themselves encrypted using the key of the parent folder, so that if you can decrypt a folder's key, you can decrypt all its descendants' keys (and therefore their names and documents' contents). The file key encrypted with its parent folder's key is called the `folder_access_key`. The way users get access to files is `user_access_keys`, which are that same file key encrypted instead using a user's public key (asymmetric encryption). When you create an account, you generate your keypair and create a user access key for yourself on your root folder. When you share a file, you create a user access key for another user on that file.

So, if you want to know the total number of shares, you're looking for the number of user access keys that are not on file tree roots. If you want to know the number of users that have shared files or had files shared with them, you're looking for the number of distinct file trees with a user access key not on a file tree root.

Note that a `ServerTree`, the file tree that the server constructs for a user for most of its purposes, includes any files shared with the user. If you want/need to know who owns the file you can check the `owner` field and if you want/need to know who shared the file you can check the `sharer_public_key` field on the `user_access_key` (it's not always the owner, since when a file is shared with you with read access you can share it with someone else with read access) and if you want/need to know who the file was shared with you can check the `sharee_public_key` field on the `user_access_key`. Shares are never forgotten, just marked deleted (using the `deleted` field), so you should think about whether you want to consider deleted shares in your metrics, and that still counts as sharing activity.
