### ISSUE TITLE
investigate bitwarden causing lockbook to freeze while trying to import from it on iOS

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#1531]

**Comment by SmailBarkouch** [comment]
Seems that lockbook is not crashing, but instead bitwarden is not closing fully when it should. I determined this when rotating the device, after "exiting" bitwarden by clicking the empty area to the side. Bitwarden would pop up again, and if I clicked the empty space, lockbook would freeze once more.

If I instead pressed the "exit" button, bitwarden would fully close and lockbook would not experience a freeze. So this issue is from bitwarden.
