### ISSUE TITLE
Editor crash

### ISSUE THREAD

**Issue by mkoloberdin** [lockbook/lockbook#1867]
Latest update (0.7.5) crashes both on Linux and MacOS for me on one of my md files. On Linux it displays the following error message in the console:
```
thread 'main' panicked at 'begin <= end (6792 <= 6791) when slicing `
Beginning of the contents of the md file here
`[...]', libs/editor/egui_editor/src/bounds.rs:23:22
```

**Comment by tvanderstad** [comment]
Thanks for submitting an issue! If you can share an example document that reproduces the issue, I'll make sure the editor doesn't crash for that case in the next release. Otherwise I'll fix a crash I experienced when the document contents are `1. *` ([related issue](https://github.com/lockbook/lockbook/issues/1871)) and wait for you to confirm your issue is fixed after we release.

**Comment by Parth** [comment]
@mkoloberdin any chance you have a minimal reproducible text that would help us identify whether #1880 actually resolves what you experienced?

**Comment by tvanderstad** [comment]
Our latest release fixed all known crashes. If your issue persists, feel free to open another issue. Thanks for raising!
