### ISSUE TITLE
Markdown syntax highlighting refinements

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#204]
Only show markdown syntax highlighting for `.md` documents.

@SmailBarkouch to inform design of refinements:

+ How much control over the markdown editor does the `markwon` editor give us?
+ Can we control the size of various nodes (headings for example)
+ Can we control which font certain elements / nodes / regions use? Could we do `monospace` for code blocks and normal for other regions?
+ Can we make various markdown elements different colors?
+ How are these themes defined? Could we easily define dark / light / Halloween / etc themes?
+ How easy would it be to make links clickable and replace images with their actual image content (not sure if we want to do this, just curious).

**Comment by SmailBarkouch** [comment]
My conclusions come from the markwon [documentation](https://noties.io/Markwon/docs/v4/editor/#getting-started-with-editor). Though not a lot of information is given about what you can do with the editor.

- How much control over the markdown editor does the markwon editor give us?
It seems we are able to customize the look of markdown when it is completed. What I mean by this is if I make text bold with `**`, rather than giving a blue tint as I do right now, I can instead make the text bold.

- Can we control the size of various nodes (headings for example)
It seems possible based on the additional handling [here](https://noties.io/Markwon/docs/v4/editor/#additional-handling). If you are speaking in terms of how it looks once we parsed the markdown, yes we can.

- Can we control which font certain elements / nodes / regions use? Could we do monospace for code blocks and normal for other regions?
Yeah we can.

- Can we make various markdown elements different colors?
Yeah we can.

- How are these themes defined? Could we easily define dark / light / Halloween / etc themes?
We could in theory based on [this](https://noties.io/Markwon/docs/v4/core/theme.html#link-color). I can just use shared preferences and set this accordingly.

- How easy would it be to make links clickable and replace images with their actual image content (not sure if we want to do this, just curious).
I actually don't know this one. Since the documentation is short, I don't exactly think there is a way to do this in the editor itself. If you are talking about when it is parsed, we can. But also, I think there is a way to just add it in dynamically by myself.
