### ISSUE TITLE
Tabs cause margins to change

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2322]

**Comment by ad-tra** [comment]
![image](https://github.com/lockbook/lockbook/assets/66345861/efb1708b-02be-436e-9662-568ab75e4033)

**Comment by ad-tra** [comment]
requested by @mahakanakala

**Comment by ad-tra** [comment]
This root of this issue is the inability to scroll through the tab strip. I added that in https://github.com/lockbook/lockbook/pull/2280/commits/2a05c1bb0c4fdd8b0efd812c3555e70360fb820b  and as a result this issue is fixed. Now there won't be a weird margin offset when you open more tabs than the width of your screen fits.
