### ISSUE TITLE
release 0.9.0

### ISSUE THREAD

**Issue by Parth** [lockbook/lockbook#2413]
+ [x] QA 0.8.5 Platform Lead Shadow
+ [x] QA iOS @tvanderstad & @smailbarkouch 
+ [x] QA iPad @Parth & @smailbarkouch 
+ [x] QA macOS @smailbarkouch & @ad-tra 
+ [x] QA Android @ad-tra & @Parth 
+ [x] QA egui @Parth & @ad-tra 
+ [x] QA windows @tvanderstad & @ad-tra 
+ [x] QA linux @ad-tra & @tvanderstad 
+ [x] QA CLI & lb-fs @smailbarkouch & @Parth

**Comment by Parth** [comment]
CLI QA Notes:
+ stream missing docs
+ `lockbook account status` bad timestamp (renews on), bad usage info 
+ zsh tab completions insert space after folder annoying
+ no tab completions for local files
+ debug info can be more useful
+ cannot author new file via `stream in`
+ check if unmount succeeded

**Comment by smailbarkouch** [comment]
CLI QA Video: https://drive.google.com/file/d/1LS3moqPCtfA_P2bf8AUSOkKybEbgVgMr/view?usp=sharing

**Comment by CoreyCole** [comment]
macos crash on create document in a new folder:
<img width="1586" alt="image" src="https://github.com/lockbook/lockbook/assets/4467106/a748e11d-d882-4a4f-ba8b-424b23254e62">

**Comment by Parth** [comment]
Android QA:
+ search is broken in 2 ways, sometimes during search, sometimes onResume
+ animation shadow for pull to refresh gets stuck sometimes
+ possible fps issues while scrolling md documents
+ selection handles small (also checkboxes)
+ back button gesture hits scroll bars in documents
+ rename icon a little unclear, other apps use context menu for rename
+ nothing pulls you into hamburger menu if you have pending shares 
+ hide red & write access list if shares are empty
+ possibly have some explanation about what that bottom section is in share file
+ platform wide we don't really respect read/write permissions
+ share externally causes shared app (messages for instance) to appear as lockbook in recent apps
+ adam idea: pending shares: can replace icons with text because we have room. Long pressing doesn't explain those icons (only reject all)
+ after we create the link it should transfer you to link location
+ not sure if bug: create a folder see sync status (1 file to push) delete folder without syncing see sync status (still 1 file to push) unsure if expected behavior.
+ widgets would be nice (3 types)
+ think through subscriptions as a team 
+ logs are broken in known ways

**Comment by ad-tra** [comment]
egui QA 
- [ ] icons are white when a modal is open
- [ ] sync message outdated 
- [ ] image pan 
- [ ] image overflows file tree
- [ ] canvas: scale is wrong from the left 
- [ ] canvas: selection bounding box is overflows 
- [ ] canvas: differentiate between shift and ctrl multi select 
- [ ] file tree: animations would be nice 
- [ ] file tree: when you drag a file, it can scroll to infinity 
- [ ] file tree: scrolls horizontally when not needed
- [ ] make all keyboard shortcuts cmd or ctrl instead of just ctrl

**Comment by Parth** [comment]
android video: https://discord.com/channels/1014184997751619664/1208419213912440842/1208535762933514361
egui video: https://discord.com/channels/1014184997751619664/1208419213912440842/1208533372922499132

**Comment by ad-tra** [comment]
# Windows QA
- can't create a drawing in tablet mode
    - integration detects long presses as a left click. ()
- Windows integration is very slow whether that's
    - scrolling large md files
    - drawing is almost unusable 
- when you go into selection mode for the first time, an empty selection box is shown 
-  can't zoom in on canvas
- couldn't open a pdf because the pdfium module is missing 
- toggling zen mode doesn't shift the contents of the canvas
- canvas resize doesn't snap to the cursor
- canvas scale doesn't collectively scale items together (swing) 
- can't delete in tablet mode in selection 
- canvas: path stops drawing after the hover instead of after lifting off the pen
- egui can not shut down the app gracefully
- egui dragging files is very finicky 
- dropping a file doesn't work 
- file picker is cropped off. it's centered relative to the workspace but when the window is smaller than workspace width it should be centered relative to the screen.
- can't scroll through the image, plus large images overflood workspace 
- md editor has external padding that is drawn over the sidebar 
- can't hide cursor on canvas
- ideally, even if the cursor hover is over an empty text region the cursor icon should still be the text cursor icon
- tab strip x is not centered
- delete, deletes the open thing in workspace instead of the selected 
- offline mode doesn't work on egui because the error text does not wrap 
    

# linux QA
- resizing the image causes a lot of issues in resizing the sidebar 
- moving files doesn't work on Linux.
- copying text breaks the ability to change tab groups within the window manager  
- cursor hide doesn't work 
- opening a lookbook link (or any unsupported link) caused the app to crash
- note to me: workspace change selected_file from pushing it every frame to only pushing it on a diff 
- canvas: can't switch focused tool based on keyboard

**Comment by smailbarkouch** [comment]
# ios QA:
+ general
	+ after inital sync, pending shares indicator is shown despite no pending shares
	+ cannot select multiple files
	+ back button should appear in toolbar when in folder
	+ file list edges become sharp when dragging out of a folder
	+ make list denser
	+ the create folder sheet has no create button
+ editor
	+ pressing and holding the toolbar button shows tooltip for an instance
	+ need more toolbar buttons
	+ context menu
		+ copy, paste, and select should appear ealier
		+ is not shown consistently
	+ floating cursor does not have the native behavior
	+ sometimes difficult to select the end of a line of text
	+ opening a document link won't change the title
+ canvas
	+ toolbar is wider than the screen
	+ strokes look pixelated
	+ cannot pan or zoom
+ pdf view
	+ cannot pan or zoom
	+ scrollbars are difficult to grab
+ image view
	+ cannot pan or zoom
+ move sheet
	+ folders show up in a different order each time
	+ all folders are expanded by default (privacy concern)
+ rename sheet
	+ should automatically focus the keyboard
	+ rename error message looks weird
+ share document sheet
	+ refine UX
	+ "username" hint should be more specific
+ settings
	+ server URL should not have its own screen
	+ cancel subscription button does not fill width and does not button style
+ search
	+ search flashes white when in progress
	+ sometimes pressed search results don't open

# macos QA
+ general
	+ we use SF font for workspace
	+ sidebar width is too small by default
	+ rename sheet needs more padding
	+ deleting a document should have a confirmation UI
	+ moving a document into the same directory show "file moved" toast
	+ pending shares screen takes up a lot of space
	+ pending shares button should appear pressed when open
	+ you can open multiple instances of lockbook and workspace using the "show tab bar" in the menu bar
+ file tree
	+ creating a new document (for where there isn't any document named "untitled") will not automatically open that document
	+ renaming or deleting the active document won't affect the workspace tab immediately
	+ cannot open an already selected document in the file tree without clicking somewhere else first
	+ not new drawing shortcut
+ share document sheet
	+ refine UX
+ document search
	+ jumps up and down a lot
	+ takes up more space than is needed sometimes
+ search
	+ searchbar should be in the sidebar
	+ search results whos parents are root will have empty text for indicating its parent
