### ISSUE TITLE
Remove distinction between new and edit across the stack

### ISSUE THREAD

**Issue by SmailBarkouch** [lockbook/lockbook#501]
Stopping CLI will cause it to try to sync the same items as before, resulting with a FileIdTaken error, and at times it may keep syncing the same exact file.

<img width="760" alt="Screen Shot 2021-01-04 at 6 31 26 PM" src="https://user-images.githubusercontent.com/20663038/103590204-3d589b00-4ebb-11eb-8164-1dce14a1e507.png">

**Comment by Parth** [comment]
Can you explain how you entered this state? Steps to repro?

**Comment by SmailBarkouch** [comment]
1. Create a bunch of files in Lockbook CLI (in this case, it was 100, but it may be as little as it needs to be to reliably do the next steps).
2. Sync Lockbook, while it is syncing exit using Ctrl + C or whatever equivalent shortcut
3. Repeat this as many times possible until the file you used Ctrl + C on one of the many repeats fails to sync.

**Comment by Parth** [comment]
got it

**Comment by Parth** [comment]
This happens because core creates a new file in the server and is terminated before it can mark it as successfully created. When it tries again the file already exists. This is an ID conflict and there's no reasonable way to resolve this. Merging the `new` and `edit` codepaths allow clients to handle this scenario more gracefully. Furthermore the distinction serves no purpose as a `metadata_version == 0` check signals the same thing to the server.
